const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1A73E8",
    background: "#FFFFFF",
    foreground: "#1A1A1A",
    card: "#F5F5F5",
    cardForeground: "#1A1A1A",
    primary: "#1A73E8",
    primaryForeground: "#FFFFFF",
    secondary: "#EEEEEE",
    secondaryForeground: "#1A1A1A",
    muted: "#EEEEEE",
    mutedForeground: "#888888",
    accent: "#1A73E8",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0E0",
    input: "#E0E0E0",
    playerBg: "#F5F5F5",
    playerSurface: "#EEEEEE",
    tabActive: "#1A73E8",
    separator: "#E0E0E0",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#A0A0A0",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#111111",
    cardForeground: "#FFFFFF",
    primary: "#FFFFFF",
    primaryForeground: "#000000",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#FFFFFF",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#222222",
    input: "#222222",
    playerBg: "#111111",
    playerSurface: "#1A1A1A",
    tabActive: "#FFFFFF",
    separator: "#222222",
  },
  radius: 8,
};

export default colors;
